# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Ingredient.create(name: 'Carotte(s)')
Ingredient.create(name: 'Chocolat')
Ingredient.create(name: 'Farine')
Ingredient.create(name: 'Oeuf(s)')
Ingredient.create(name: 'Ail')
Ingredient.create(name: 'Pois Chiches')
Ingredient.create(name: 'Tomate(s)')
Ingredient.create(name: 'Oignon(s) roses de Bretagne')
Ingredient.create(name: 'Mozarella')
Ingredient.create(name: 'Avocat(s)')
Ingredient.create(name: 'Basilic')
Ingredient.create(name: 'Coriandre')
Ingredient.create(name: 'Mâche')
Ingredient.create(name: 'Roquette')
Ingredient.create(name: 'Potiron(s)')
Ingredient.create(name: 'Butternut(s)')
Ingredient.create(name: 'Lait de Coco')
Ingredient.create(name: 'Sel')
Ingredient.create(name: 'Poivre')
Ingredient.create(name: 'Cumin')
Ingredient.create(name: 'Paprika')
Ingredient.create(name: 'Huile Olive')
Ingredient.create(name: 'Curry')
Ingredient.create(name: 'Gingembre')
Ingredient.create(name: 'Pommme(s) de terre')
Ingredient.create(name: 'Lait')
Ingredient.create(name: 'Patate(s) douce(s)')
Ingredient.create(name: 'Pâte Brisée')
Ingredient.create(name: 'Pesto')
Ingredient.create(name: 'Thon émietté')
Ingredient.create(name: 'Pain')
Ingredient.create(name: 'Herbes aromatiques')
Ingredient.create(name: 'Sel')
Ingredient.create(name: 'Bière')
Ingredient.create(name: 'Maïzena')
Ingredient.create(name: 'Poisson blanc')
Ingredient.create(name: 'Bière')
Ingredient.create(name: 'Eau')
Ingredient.create(name: "Blanc(s) d'oeufs")
Ingredient.create(name: "Jaune(s) d'oeufs")
Ingredient.create(name: "Gruyère")
Ingredient.create(name: "Persil")
Ingredient.create(name: "Panais")
Ingredient.create(name: "Piment d' Espelette")
Ingredient.create(name: "De l'amour")
Ingredient.create(name: "Potimarron(s)")


Category.create(name: 'Végétarien')
Category.create(name: 'Sucré')
Category.create(name: 'Entrée')
Category.create(name: 'Plat')
Category.create(name: 'Amuse-gueule')

